"""empty message

Revision ID: 43ec72e28518
Revises: 30ceabaad536
Create Date: 2016-03-16 20:03:03.921000

"""

# revision identifiers, used by Alembic.
revision = '43ec72e28518'
down_revision = '30ceabaad536'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
