"""empty message

Revision ID: 63610fcaafaa
Revises: 11615341a320
Create Date: 2016-03-04 20:58:21.403000

"""

# revision identifiers, used by Alembic.
revision = '63610fcaafaa'
down_revision = '11615341a320'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
