"""empty message

Revision ID: 7b455efcdfbb
Revises: 11615341a320
Create Date: 2016-03-04 20:06:47.908000

"""

# revision identifiers, used by Alembic.
revision = '7b455efcdfbb'
down_revision = '11615341a320'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
