"""empty message

Revision ID: 90725cca174e
Revises: abe2bff2f5bd
Create Date: 2016-02-29 10:34:57.206000

"""

# revision identifiers, used by Alembic.
revision = '90725cca174e'
down_revision = 'abe2bff2f5bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
