"""empty message

Revision ID: 93e07172089
Revises: 4334bc4911a3
Create Date: 2016-03-01 15:20:28.466000

"""

# revision identifiers, used by Alembic.
revision = '93e07172089'
down_revision = '4334bc4911a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
